export const data = [
    {
        id: 1,
        permalink: "https://link.com/1",
        datePublished: "01/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting BTS", 
        currentViews: 12458,
        subsAdded: 12,
        watchHours: 72,
    },
    {
        id: 2,
        permalink: "https://link.com/2",
        datePublished: "02/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Berlin", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 3,
        permalink: "https://link.com/3",
        datePublished: "03/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Mexico", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 4,
        permalink: "https://link.com/4",
        datePublished: "04/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Velo",
        campaignName: "Archie Hamilton",
        title: "ATV Riding in Sweden", 
        currentViews: 1983,
        subsAdded: 8,
        watchHours: 12,
    },
    {
        id: 5,
        permalink: "https://link.com/5",
        datePublished: "05/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting BTS", 
        currentViews: 12458,
        subsAdded: 12,
        watchHours: 72,
    },
    {
        id: 6,
        permalink: "https://link.com/6",
        datePublished: "06/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Berlin", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 7,
        permalink: "https://link.com/7",
        datePublished: "07/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Mexico", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 8,
        permalink: "https://link.com/8",
        datePublished: "08/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Velo",
        campaignName: "Archie Hamilton",
        title: "ATV Riding in Sweden", 
        currentViews: 1983,
        subsAdded: 8,
        watchHours: 12,
    },
    {
        id: 9,
        permalink: "https://link.com/9",
        datePublished: "09/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting BTS", 
        currentViews: 12458,
        subsAdded: 12,
        watchHours: 72,
    },
    {
        id: 10,
        permalink: "https://link.com/10",
        datePublished: "10/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Berlin", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 11,
        permalink: "https://link.com/11",
        datePublished: "11/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Mexico", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 12,
        permalink: "https://link.com/12",
        datePublished: "12/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Velo",
        campaignName: "Archie Hamilton",
        title: "ATV Riding in Sweden", 
        currentViews: 1983,
        subsAdded: 8,
        watchHours: 12,
    },
    {
        id: 13,
        permalink: "https://link.com/13",
        datePublished: "13/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting BTS", 
        currentViews: 12458,
        subsAdded: 12,
        watchHours: 72,
    },
    {
        id: 14,
        permalink: "https://link.com/14",
        datePublished: "14/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Berlin", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 15,
        permalink: "https://link.com/15",
        datePublished: "15/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Vuse",
        campaignName: "On the Road with Dom",
        title: "Dom Whiting: Mexico", 
        currentViews: 124583,
        subsAdded: 29,
        watchHours: 92,
    },
    {
        id: 16,
        permalink: "https://link.com/16",
        datePublished: "16/05/2022",
        platform: "YouTube",
        contentType: "Video",
        brand: "Velo",
        campaignName: "Archie Hamilton",
        title: "ATV Riding in Sweden", 
        currentViews: 1983,
        subsAdded: 8,
        watchHours: 12,
    },
];

